name: CD Pipeline

on:
  workflow_run:
    types:
      - completed
jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: sudo docker pull davorstefanovski/hservice:latest
      - name: Delete old docker container
        run: sudo docker rm -f hservice-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name hservice-container davorstefanovski/hservice



